=== jmullan/Gallery2/lib/tools/dtd/DatabaseTableDefinition2.0.dtd
<!ELEMENT table ( table-name, schema, column+, (key | index)* ) >

<!ELEMENT schema ( schema-major, schema-minor ) >
<!ELEMENT column ( column-name, column-type, column-size, not-null?, default? ) >
<!ELEMENT key ( column-name+ ) >
<!ELEMENT index ( column-name+ ) >

<!ELEMENT table-name ( #PCDATA ) >
<!ELEMENT schema-major ( #PCDATA ) >
<!ELEMENT schema-minor ( #PCDATA ) >
<!ELEMENT column-name ( #PCDATA ) >
<!ELEMENT column-type ( #PCDATA ) >
<!ELEMENT column-size ( #PCDATA ) >
<!ELEMENT not-null EMPTY >
<!ELEMENT default ( #PCDATA ) >
<!ATTLIST key primary (true | false) "false">
<!ATTLIST not-null empty (allowed | disallowed) "disallowed">

=== jmullan/Gallery2/modules/quotas/classes/GalleryStorage/DatabaseStorage/schema/xml-out/QuotasMap.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE table
  SYSTEM "../../../../../../../lib/tools/dtd/DatabaseTableDefinition2.0.dtd">
<table>
   <table-name>QuotasMap</table-name>
   <schema>
      <schema-major>1</schema-major>
      <schema-minor>0</schema-minor>
   </schema>
   <column>
      <column-name>userOrGroupId</column-name>
      <column-type>INTEGER</column-type>
      <column-size>MEDIUM</column-size>
   </column>
   <column>
      <column-name>quotaSize</column-name>
      <column-type>INTEGER</column-type>
      <column-size>MEDIUM</column-size>
      <not-null empty="disallowed"/>
   </column>
   <index>
      <column-name>userOrGroupId</column-name>
   </index>
</table>
