=== jmullan/Gallery2/lib/tools/dtd/GalleryClass2.0.dtd
<!ELEMENT class ( class-name, schema, requires-id?, (map | member+)? ) >

<!ELEMENT schema ( schema-name, schema-major, schema-minor ) >
<!ELEMENT map ( member+, key? ) >
<!ELEMENT member ( member-name, member-type, member-size?, id?, (indexed | unique)?, required? ) >
<!ELEMENT key ( member-name+ ) >

<!ELEMENT class-name ( #PCDATA ) >
<!ELEMENT schema-name ( #PCDATA ) >
<!ELEMENT schema-major ( #PCDATA ) >
<!ELEMENT schema-minor ( #PCDATA ) >
<!ELEMENT member-name ( #PCDATA ) >
<!ELEMENT member-type ( #PCDATA ) >
<!ELEMENT member-size ( #PCDATA ) >
<!ELEMENT requires-id EMPTY >
<!ELEMENT required EMPTY >
<!ELEMENT indexed EMPTY >
<!ELEMENT unique EMPTY >
<!ELEMENT id EMPTY >

=== jmullan/Gallery2/modules/quotas/classes/GalleryStorage/DatabaseStorage/schema/xml-src/tmp/QuotasMap.xml
<!DOCTYPE class SYSTEM "../../../../../../../../lib/tools/dtd/GalleryClass2.0.dtd">
<class>
<class-name>QuotasMap</class-name>
<schema>
<schema-name>QuotasMap</schema-name>
<schema-major>1</schema-major>
<schema-minor>0</schema-minor>
</schema>
<map>
<member>
<member-name>userOrGroupId</member-name>
<member-type>INTEGER</member-type>
</member>
<member>
<member-name>quotaSize</member-name>
<member-type>INTEGER</member-type>
<required/>
</member>
<index>
<member-name>userOrGroupId</member-name>
</index>
</map>
</class>
