=== jmullan/Gallery2/lib/tools/dtd/MapsDefinition2.0.dtd
<!ELEMENT maps ( map* ) >
<!ELEMENT map ( map-name, schema, member+, key?, index* ) >
<!ELEMENT member ( member-name, member-type, member-size?, id?, (indexed | unique)?, required?, primary?, default? ) >
<!ELEMENT schema ( schema-major, schema-minor ) >
<!ELEMENT key ( member-name+ ) >
<!ELEMENT index ( member-name+ ) >

<!ELEMENT map-name ( #PCDATA ) >
<!ELEMENT schema-major ( #PCDATA ) >
<!ELEMENT schema-minor ( #PCDATA ) >
<!ELEMENT member-name ( #PCDATA ) >
<!ELEMENT member-type ( #PCDATA ) >
<!ELEMENT member-size ( #PCDATA ) >
<!ELEMENT required EMPTY >
<!ELEMENT default ( #PCDATA ) >
<!ELEMENT indexed EMPTY >
<!ELEMENT unique EMPTY >
<!ELEMENT primary EMPTY >
<!ELEMENT id EMPTY >
<!ATTLIST key primary (true | false) "false">
<!ATTLIST required empty (allowed | disallowed) "disallowed">

=== jmullan/Gallery2/modules/imageblock/classes/Maps.xml
<!DOCTYPE maps SYSTEM "../../../lib/tools/dtd/MapsDefinition2.0.dtd">
<maps>
  <map>
    <map-name>ImageBlockCacheMap</map-name>
    <schema>
      <schema-major>1</schema-major>
      <schema-minor>1</schema-minor>
    </schema>
    <member>
      <member-name>userId</member-name>
      <member-type>INTEGER</member-type>
      <required/>
    </member>
    <member>
      <member-name>itemType</member-name>
      <member-type>INTEGER</member-type>
      <required/>
    </member>
    <member>
      <member-name>itemTimestamp</member-name>
      <member-type>INTEGER</member-type>
      <required/>
    </member>
    <member>
      <member-name>itemId</member-name>
      <member-type>INTEGER</member-type>
      <required/>
    </member>
    <index>
      <member-name>userId</member-name>
      <member-name>itemType</member-name>
    </index>
  </map>
  <map>
    <map-name>ImageBlockDisabledMap</map-name>
    <schema>
      <schema-major>1</schema-major>
      <schema-minor>0</schema-minor>
    </schema>
    <member>
      <member-name>itemId</member-name>
      <member-type>INTEGER</member-type>
      <primary/>
    </member>
  </map>
</maps>
